// client/src/components/Footer.jsx
import React from 'react';
import { Link } from 'react-router-dom';

export default class Footer extends React.Component {
  date = new Date();

  goToTop = () => {
    window.scrollTo(0, 0);
  };

  render() {
    return (
      <footer>
        <div className="container ">
          <div>
            Znajdź nas na facebooku:{' '}
            <a href="https://www.facebook.com/mmpzakopane" target="_blank">
              MMPZakopane
            </a>{' '}
            |{' '}
            <Link onClick={this.goToTop} to="/regulamin">
              Regulamin
            </Link>{' '}
            |{' '}
            <Link onClick={this.goToTop} to="/polecamy">
              Polecamy
            </Link>
          </div>
          <div>Copyright &copy; {this.date.getFullYear()} by MMPStudio.pl | All rights reserved.</div>
        </div>
      </footer>
    );
  }
}

// components/Footer.vue
<template>
  <footer class="footer secondary py-10">
    <v-container class="footer__container footer-font--text">
      <div class="footer__info">
        <span>Znajdź nas na facebooku:</span>
        <a
          class="footer__link"
          href="https://www.facebook.com/mmpzakopane"
          target="_blank"
          >MMPZakopane</a
        >
        <span class="px-1">|</span>
        <nuxt-link
          class="footer__link"
          to="/regulamin"
          >Regulamin</nuxt-link
        >
        <span class="px-1">|</span>
        <nuxt-link
          class="footer__link"
          to="/polecamy"
          >Polecamy</nuxt-link
        >
      </div>
      <div class="footer__copyright">
        Copyright &copy; {{ new Date().getFullYear() }} by MMPStudio | All
        rights reserved.
      </div>
    </v-container>
  </footer>
</template>

<script>
export default {
  name: 'MmpFooter',
};
</script>

<style scoped lang="scss">
.footer {
  &__container {
    display: grid;
    grid-template-columns: minmax(0, 1fr);
    justify-items: center;
    gap: 1rem;
    text-align: center;
    @media #{$md-and-up} {
      grid-template-columns: repeat(2, minmax(0, max-content));
      justify-content: space-between;
      text-align: unset;
    }
  }
  &__link {
    color: var(--v-link-base);
    text-decoration: none;
    transition: 0.2s $cubic-bezier;
    font-weight: bold;
    &:hover {
      color: var(--v-primary-base);
    }
  }
}
</style>
